import React from 'react';
import { Waves, ShieldAlert, Cpu, Globe, CheckCircle2, Award, BookOpen, Lock } from 'lucide-react';
import { SectionHeader } from '../components/SectionHeader';
import { StatusBadge } from '../components/StatusBadge';
import { AlertPanel } from '../components/AlertPanel';
import { Card } from '../components/Card';

export const AboutPage: React.FC = () => {
  return (
    <div className="space-y-10 pb-12">
      {/* HEADER */}
      <SectionHeader
        title="About TsunamiSense AI"
        subtitle="Intelligent Tsunami Risk Detection & Early-Warning Decision Support prototype built for the IBM Datathon."
        badge={<StatusBadge label="IBM DATATHON PROJECT" variant="accent" size="sm" />}
      />

      {/* OVERVIEW HERO BANNER */}
      <div className="p-8 rounded-2xl border border-slate-800 bg-gradient-to-br from-[#0a1428] via-[#060d1a] to-[#040812] shadow-2xl space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
              <Waves className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-2xl font-display font-extrabold text-slate-100">TSUNAMISENSE AI</h2>
              <p className="text-xs font-mono text-cyan-300">IBM Datathon Research Initiative</p>
            </div>
          </div>
          <StatusBadge label="RESEARCH & DECISION SUPPORT" variant="info" />
        </div>

        <p className="text-sm text-slate-300 leading-relaxed font-sans max-w-3xl">
          TsunamiSense AI is a decision-support platform designed to estimate earthquake-generated tsunami potential by combining seismic intelligence, bathymetric GIS data, historical tsunami catalogs, ocean observation buoy networks, and explainable AI reasoning.
        </p>
      </div>

      {/* PROBLEM & SOLUTION */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card header={<h3 className="font-display font-bold text-base text-slate-100">1. The Problem</h3>}>
          <div className="space-y-3 text-xs text-slate-300 leading-relaxed font-sans">
            <p>
              Tsunamis generated by undersea subduction earthquakes can strike coastal regions within 15 to 30 minutes of seismic rupture. Traditional warning pipelines often rely on single-source seismic thresholds or complex numerical wave propagation simulations that take significant compute time.
            </p>
            <p>
              Disaster responders need rapid, multi-source evidence synthesis that combines initial seismic estimates with bathymetry, subduction geometry, and historical benchmark precedents before buoy observations are fully available.
            </p>
          </div>
        </Card>

        <Card header={<h3 className="font-display font-bold text-base text-slate-100">2. The Solution</h3>}>
          <div className="space-y-3 text-xs text-slate-300 leading-relaxed font-sans">
            <p>
              TsunamiSense AI establishes a multi-source intelligence engine that fuses seismic feeds ($M_w$, depth, epicenter, fault geometry) with bathymetric slope datasets and historical event analogs.
            </p>
            <p>
              By coupling machine learning estimation with Google Gemini LLM reasoning, the platform produces immediate, explainable decision support summaries for emergency management analysts.
            </p>
          </div>
        </Card>
      </div>

      {/* TECHNOLOGY STACK */}
      <Card header={<h3 className="font-display font-bold text-base text-slate-100">3. Technology Architecture</h3>}>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-xs font-sans">
          <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
            <div className="font-mono text-cyan-400 font-semibold uppercase">Frontend System</div>
            <p className="text-slate-300">React 19, TypeScript, Tailwind CSS v4, Motion, Lucide Icons</p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
            <div className="font-mono text-amber-400 font-semibold uppercase">Data Feeds (Phase 1)</div>
            <p className="text-slate-300">USGS Earthquake API, NOAA NCEI Historical Database, DART Buoys</p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
            <div className="font-mono text-indigo-400 font-semibold uppercase">ML Engine (Phase 2)</div>
            <p className="text-slate-300">Gradient Boosted Trees, Seafloor Displacement Physics, SHAP Explainability</p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
            <div className="font-mono text-sky-400 font-semibold uppercase">AI Reasoning (Phase 4)</div>
            <p className="text-slate-300">Google GenAI SDK, Gemini LLM Natural Language Rationale</p>
          </div>
        </div>
      </Card>

      {/* RESPONSIBLE AI & SAFETY PRINCIPLES */}
      <Card header={<h3 className="font-display font-bold text-base text-slate-100">4. Responsible AI & Safety Principles</h3>}>
        <div className="space-y-4 text-xs text-slate-300 leading-relaxed font-sans">
          <div className="flex items-start gap-3">
            <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-slate-200 block font-semibold">Human-in-the-Loop Decision Support</strong>
              <span>TsunamiSense AI is explicitly engineered as a decision-support tool for trained analysts, not an autonomous emergency dispatcher.</span>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <Lock className="w-5 h-5 text-cyan-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-slate-200 block font-semibold">No Fake Scientific Predictions</strong>
              <span>The platform enforces strict data transparency. In the absence of live API feeds or calibrated ML models, data states are explicitly designated as "Data Engine Offline" rather than displaying simulated metrics.</span>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <BookOpen className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-slate-200 block font-semibold">Alignment with Official Tsunami Warning Centers</strong>
              <span>All platform views explicitly direct emergency responders to authoritative state agencies (PTWC, JMA, NOAA, USGS, BMKG).</span>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
};
